# Generated by Django 5.0.6 on 2024-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_address_customuser_city_customuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='myapp.product'),
        ),
    ]
